mode:
  development

###############datasource config##################
#mysql,mongodb,redis等数据源配置方式
development:
    datasources:
        mysql:
           host: 127.0.0.1
           port: 3306
           database: pento_cloud_dev
           username: root
           password: mysql
           disable: false
        mongodb:
           host: 127.0.0.1
           port: 27017
           database: csdn_data_center
           disable: false
        redis:
            host: 127.0.0.1
            port: 6379
            disable: false
        filestore:
            path: /tmp/data/static
            url: http://localhost:9500/static

test:
    datasources:
        mysql:
           host: 127.0.0.1
           port: 3306
           database: pento_cloud_test
           username: root
           password: mysql
           disable: false
        mongodb:
           host: 127.0.0.1
           port: 27017
           database: csdn_data_center
           disable: false
        redis:
            host: 127.0.0.1
            port: 6379
            disable: true
        filestore:
            path: /tmp/data/static
            url: http://localhost:9500/static

production:
    datasources:
        mysql:
           host: 127.0.0.1
           port: 3306
           database: pento_cloud_prod
           username: root
           password: mysql
        mongodb:
           host: 127.0.0.1
           port: 27017
           database: csdn_data_center
        redis:
            host: 127.0.0.1
            port: 6379
        filestore:
            path: /tmp/data/static
            url: http://localhost:9500/static

orm:
    show_sql: true
    pool_min_size: 5
    pool_max_size: 10
    timeout: 300
    max_statements: 50
    idle_test_period: 3000

###############application config##################
#'model' for relational database  like MySQL
#'document' for NoSQL database model configuration,  MongoDB

application:
    controller: com.xn.pento.controller
    model:      com.xn.pento.model
    document:   com.xn.pento.document
    service:    com.xn.pento.service
    util:       com.xn.pento.util
    test:       test.com.xn.pento
    servlet:    api,manage



###############http config##################
http:
    port: 9500

###############validator config##################
#如果需要添加验证器，只要配置好类全名即可
#替换验证器实现，则替换相应的类名即可
#warning: 自定义验证器实现需要线程安全

validator:
   format:        net.csdn.validate.impl.Format
   numericality:  net.csdn.validate.impl.Numericality
   presence:      net.csdn.validate.impl.Presence
   uniqueness:    net.csdn.validate.impl.Uniqueness
   length:        net.csdn.validate.impl.Length
   associated:    net.csdn.validate.impl.Associated

mongo_validator:
   format:        net.csdn.mongo.validate.impl.Format
   numericality:  net.csdn.mongo.validate.impl.Numericality
   presence:      net.csdn.mongo.validate.impl.Presence
   uniqueness:    net.csdn.mongo.validate.impl.Uniqueness
   length:        net.csdn.mongo.validate.impl.Length
   associated:    net.csdn.mongo.validate.impl.Associated

################ 数据库类型映射 ####################
type_mapping:  net.csdn.jpa.type.impl.MysqlType
